version: '3'
services:
    postgres:
        image: postgres:latest
        container_name: postgres
        restart: always
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
          - POSTGRES_DB=user_db
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - '54321:5432'

networks:
  elastic:
    driver: bridge